# Generated by Django 5.0.6 on 2025-12-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_link_click_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avatar_url",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.FileField(blank=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_total_clicks",
            field=models.BooleanField(
                default=True, help_text="Show the total click count across all links"
            ),
        ),
    ]
