# Generated by Django 5.0.6 on 2025-12-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_remove_profile_avatar_url_profile_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="icon_image",
            field=models.FileField(blank=True, upload_to="link_icons/"),
        ),
    ]
