# Generated by Django 5.0.6 on 2025-12-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0004_link_icon_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="show_discount_badge",
            field=models.BooleanField(
                default=False, help_text="Show a 할인 badge on the link"
            ),
        ),
        migrations.AddField(
            model_name="link",
            name="show_popular_badge",
            field=models.BooleanField(
                default=False, help_text="Show an 인기 badge on the link"
            ),
        ),
    ]
