# Generated by Django 5.0.6 on 2025-12-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0005_link_show_discount_badge_link_show_popular_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="hashtags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated hashtags (without #)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="thread_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
    ]
