# Generated by Django 5.0.6 on 2026-03-10 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_link_hashtags_profile_facebook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoDrawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_round', models.PositiveIntegerField(unique=True, verbose_name='추첨회차')),
                ('draw_date', models.DateField(unique=True, verbose_name='추첨일자')),
                ('draw_date_code', models.CharField(max_length=8, unique=True, verbose_name='추첨일자(yyyymmdd)')),
                ('winning_numbers', models.JSONField(default=list, verbose_name='당첨번호')),
                ('bonus_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='보너스 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '로또 실제 추첨 결과',
                'verbose_name_plural': '로또 실제 추첨 결과',
                'ordering': ['-draw_date', '-draw_round'],
            },
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='세션 키')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('ticket_numbers', models.JSONField(default=list, verbose_name='추첨번호')),
                ('draw_date', models.DateField(db_index=True, verbose_name='추첨일자')),
                ('draw_date_code', models.CharField(db_index=True, max_length=8, verbose_name='추첨일자(yyyymmdd)')),
                ('draw_round', models.PositiveIntegerField(db_index=True, verbose_name='추첨회차')),
                ('matched_numbers', models.JSONField(blank=True, default=list, verbose_name='일치 번호')),
                ('matched_count', models.PositiveSmallIntegerField(default=0, verbose_name='일치 개수')),
                ('matched_bonus', models.BooleanField(default=False, verbose_name='보너스 번호 일치')),
                ('prize_rank', models.PositiveSmallIntegerField(blank=True, choices=[(0, '낙첨'), (1, '1등'), (2, '2등'), (3, '3등'), (4, '4등'), (5, '5등')], null=True, verbose_name='당첨 등수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draw_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='links.lottodrawresult', verbose_name='실제 추첨 결과')),
            ],
            options={
                'verbose_name': '로또 티켓',
                'verbose_name_plural': '로또 티켓',
                'ordering': ['-created_at'],
            },
        ),
    ]
